export type CongressMember = {
  address: string;
  bioguideid: string;
  birthyear: string;
  chamber: string;
  cosponsorelegislationcount: number;
  currentember: boolean;
  directordername: string;
  district: number;
  firstname: string;
  honorificname: string;
  imageurl: string;
  invertedordername: string;
  lastname: string;
  middlename: string;
  officialwebsiteurl: string;
  partyabbreviation: string;
  partyname: string;
  phonenumber: string;
  sponsoredlegislationcount: number;
  state: string;
  termcount: number;
};
